### ISSUE TITLE
can the license be changed ? 

### ISSUE THREAD

**Issue by koloved** [wjakob/instant-meshes#107]
Is it possible that the license will be changed? This application can be in blender! Thank you! 

[https://youtu.be/I4b6DM6f1OQ?t=2897](https://youtu.be/I4b6DM6f1OQ?t=2897)

**Comment by wjakob** [comment]
I found this video very funny :-). The license is a BSD license, so there is not much that one can do in making it even more open...

**Comment by ProgrammingLife** [comment]
@wjakob This software is awesome piece of work! 
Please keep making it better if you have some possibilities to make it even better.

**Comment by mikkorantalainen** [comment]
Could you consider dropping off the extra part that's not included in the standard 3-clause BSD?

The extra part of license in full:
> You are under no obligation whatsoever to provide any bug fixes, patches, or
upgrades to the features, functionality or performance of the source code
("Enhancements") to anyone; however, if you choose to make your Enhancements
available either publicly, or directly to the authors of this software, without
imposing a separate written license agreement for such Enhancements, **then you
hereby grant the following license: a non-exclusive, royalty-free perpetual
license to install, use, modify, prepare derivative works, incorporate into
other computer software, distribute, and sublicense such enhancements or
derivative works thereof, in binary and source code form.**

Trying to enforced the part I emphasized above could be really hard and keeping it here makes combining this code with other licenses potentially problematic. This is because it's unclear if this part is intented to be viral (that is, should this be considered to cover combined work when this code is combined with other code with e.g. MIT or GPL v2+ license). What if this code is combined with Blender (licensed with GPL v2+) and somebody publishes some enchancement to Blender without specifying license – would this part cover that or not?

Also note that you don't need to sign any license contracts to receive copy of the code. License is only needed for distribution. Even if you find some piece of code found from some public website (Enchancement without imposing a separate written license) it couldn't be safely combined with this code, because you would have to first show/verify that the publisher of said code has actually agreed to this custom license before publishing that code. Somebody reading the instant-meshes code and publishing a patch doesn't require him or her to accept the license! Anybody using such code (that is, without explicitly declared license) would potentially infringe the copyright of the creator of such patch. As a result, such a patch couldn't be safely included in the official source code. (Google "copyright troll" if you cannot see the problem here.)

As such, I fail to see any case where it would be beneficial to have this non-standard part included in the license. It cannot provide any extra value to instant-meshes and it can prevent including this code e.g. in Blender. As the rest of the license seems to be standard 3-clause BSD, I'm assuming that the intent of this project is to make the code available as free software.
