### ISSUE TITLE
Help viewport

### ISSUE THREAD

**Issue by carlora** [wjakob/instant-meshes#20]
Hello everyone, I've a issue whit the tool!

I try to "open mesh" and import a project but in viewport nothing appears!

I try running  the program also whit GUI mode, but is the same...

can You help me please....

![immagine](https://cloud.githubusercontent.com/assets/17197993/13008009/33371dd0-d194-11e5-9c00-e15546d6c98f.png)

![immagine2](https://cloud.githubusercontent.com/assets/17197993/13008038/5d47938e-d194-11e5-80bf-cd6443087390.png)

![immagine23](https://cloud.githubusercontent.com/assets/17197993/13008075/83bd75c4-d194-11e5-9acb-8aef7aee54a4.png)

**Comment by carlora** [comment]
no-one to help me?

**Comment by wjakob** [comment]
Not sure there is anything we can do here. Probably there is an OpenGL-related issue with your graphics card that is preventing the geometry from rendering. I'm closing this because we'd need more detailed technical information from a developer using this graphics card to track it down to an actual part of the code that could be modified.
